sidus_autocomplete_api_attribute_search:
    path:     /_autocomplete/search/attribute/{attributePath}
    defaults: { _controller: Sidus\EAVBootstrapBundle\Action\AttributeSearchAction:__invoke }

sidus_autocomplete_api_family_search:
    path:     /_autocomplete/search/family/{familyCode}
    defaults: { _controller: Sidus\EAVBootstrapBundle\Action\FamilySearchAction:__invoke }
