sidus_autocomplete_api_attribute_search:
    path:     /_autocomplete/search/attribute/{attributePath}
    defaults: { _controller: sidus_eav_bootstrap.action.attribute_search:__invoke }

sidus_autocomplete_api_family_search:
    path:     /_autocomplete/search/family/{familyCode}
    defaults: { _controller: sidus_eav_bootstrap.action.family_search:__invoke }
